seed: 0
project:
  version: 1.0.0
run_parameters:
  run_mode: training
  state_type: grid
  state_size: 11
  hidden_size:
  - 128
  - 128
  learning_rate: 0.0025
  entropy_coeff: 0.025
  batch_size: 20
  n_episodes: 500
  gamma: 0.9
  show_episode_progress: false
env_parameters:
  w: 10
  h: 10
  reward_type: dense
  reward_values:
    food: 50
    death: -10
    step: -0.1
  max_steps_multiplier: 100
save_parameters:
  run_name: test4
  save_actor_frequency: 100
  video_seeds:
  - 1
  - 2
  - 3
